version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: carmen_goudie
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-proyecto-integrador
      dockerfile: Dockerfile
    container_name: dev-backend
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/carmen_goudie
      JWT_SECRET: nabil123
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./backend-proyecto-integrador:/app

volumes:
  db_data: