version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - ./backend-proyecto-integrador/.env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend-proyecto-integrador
      dockerfile: Dockerfile
    container_name: dev-backend
    env_file:
      - ./backend-proyecto-integrador/.env
    environment:
      # DATABASE_URL se sobreescribe aquí porque dentro de Docker el host es 'db', no 'localhost'
      DATABASE_URL: "postgres://postgres:123@db:5432/carmen_goudie"
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend-proyecto-integrador:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run start:dev"

volumes:
  db_data:
