-- Catálogo de comunas de Chile y relación universidad → comuna.
--
-- `universidad.comuna` era texto libre. Se reemplaza por una FK a un catálogo
-- para que la comuna se SELECCIONE (el texto libre producía variantes que no
-- coincidían al agrupar en los informes). La migración no pierde datos: cada
-- universidad existente se enlaza a su comuna comparando el texto normalizado
-- (minúsculas, sin tildes ni signos), y si alguna fila no encuentra comuna la
-- migración entera se aborta ANTES de borrar la columna de texto.
--
-- Fuente del catálogo: las 346 comunas con su Código Único Territorial (CUT)
-- oficial, que se usa como llave primaria.

BEGIN;

CREATE TABLE "comuna" (
    "codigo_comuna" INTEGER NOT NULL,
    "nombre"        TEXT    NOT NULL,
    "region"        TEXT    NOT NULL,

    CONSTRAINT "comuna_pkey" PRIMARY KEY ("codigo_comuna")
);

CREATE UNIQUE INDEX "comuna_nombre_key" ON "comuna"("nombre");

INSERT INTO "comuna" ("codigo_comuna", "nombre", "region") VALUES
  (1101, 'Iquique', 'Tarapacá'),
  (1107, 'Alto Hospicio', 'Tarapacá'),
  (1401, 'Pozo Almonte', 'Tarapacá'),
  (1402, 'Camiña', 'Tarapacá'),
  (1403, 'Colchane', 'Tarapacá'),
  (1404, 'Huara', 'Tarapacá'),
  (1405, 'Pica', 'Tarapacá'),
  (2101, 'Antofagasta', 'Antofagasta'),
  (2102, 'Mejillones', 'Antofagasta'),
  (2103, 'Sierra Gorda', 'Antofagasta'),
  (2104, 'Taltal', 'Antofagasta'),
  (2201, 'Calama', 'Antofagasta'),
  (2202, 'Ollagüe', 'Antofagasta'),
  (2203, 'San Pedro de Atacama', 'Antofagasta'),
  (2301, 'Tocopilla', 'Antofagasta'),
  (2302, 'María Elena', 'Antofagasta'),
  (3101, 'Copiapó', 'Atacama'),
  (3102, 'Caldera', 'Atacama'),
  (3103, 'Tierra Amarilla', 'Atacama'),
  (3201, 'Chañaral', 'Atacama'),
  (3202, 'Diego de Almagro', 'Atacama'),
  (3301, 'Vallenar', 'Atacama'),
  (3302, 'Alto del Carmen', 'Atacama'),
  (3303, 'Freirina', 'Atacama'),
  (3304, 'Huasco', 'Atacama'),
  (4101, 'La Serena', 'Coquimbo'),
  (4102, 'Coquimbo', 'Coquimbo'),
  (4103, 'Andacollo', 'Coquimbo'),
  (4104, 'La Higuera', 'Coquimbo'),
  (4105, 'Paihuano', 'Coquimbo'),
  (4106, 'Vicuña', 'Coquimbo'),
  (4201, 'Illapel', 'Coquimbo'),
  (4202, 'Canela', 'Coquimbo'),
  (4203, 'Los Vilos', 'Coquimbo'),
  (4204, 'Salamanca', 'Coquimbo'),
  (4301, 'Ovalle', 'Coquimbo'),
  (4302, 'Combarbalá', 'Coquimbo'),
  (4303, 'Monte Patria', 'Coquimbo'),
  (4304, 'Punitaqui', 'Coquimbo'),
  (4305, 'Río Hurtado', 'Coquimbo'),
  (5101, 'Valparaíso', 'Valparaíso'),
  (5102, 'Casablanca', 'Valparaíso'),
  (5103, 'Concón', 'Valparaíso'),
  (5104, 'Juan Fernández', 'Valparaíso'),
  (5105, 'Puchuncaví', 'Valparaíso'),
  (5107, 'Quintero', 'Valparaíso'),
  (5109, 'Viña del Mar', 'Valparaíso'),
  (5201, 'Isla de Pascua', 'Valparaíso'),
  (5301, 'Los Andes', 'Valparaíso'),
  (5302, 'Calle Larga', 'Valparaíso'),
  (5303, 'Rinconada', 'Valparaíso'),
  (5304, 'San Esteban', 'Valparaíso'),
  (5401, 'La Ligua', 'Valparaíso'),
  (5402, 'Cabildo', 'Valparaíso'),
  (5403, 'Papudo', 'Valparaíso'),
  (5404, 'Petorca', 'Valparaíso'),
  (5405, 'Zapallar', 'Valparaíso'),
  (5501, 'Quillota', 'Valparaíso'),
  (5502, 'La Calera', 'Valparaíso'),
  (5503, 'Hijuelas', 'Valparaíso'),
  (5504, 'La Cruz', 'Valparaíso'),
  (5506, 'Nogales', 'Valparaíso'),
  (5601, 'San Antonio', 'Valparaíso'),
  (5602, 'Algarrobo', 'Valparaíso'),
  (5603, 'Cartagena', 'Valparaíso'),
  (5604, 'El Quisco', 'Valparaíso'),
  (5605, 'El Tabo', 'Valparaíso'),
  (5606, 'Santo Domingo', 'Valparaíso'),
  (5701, 'San Felipe', 'Valparaíso'),
  (5702, 'Catemu', 'Valparaíso'),
  (5703, 'Llay-Llay', 'Valparaíso'),
  (5704, 'Panquehue', 'Valparaíso'),
  (5705, 'Putaendo', 'Valparaíso'),
  (5706, 'Santa María', 'Valparaíso'),
  (5801, 'Quilpué', 'Valparaíso'),
  (5802, 'Limache', 'Valparaíso'),
  (5803, 'Olmué', 'Valparaíso'),
  (5804, 'Villa Alemana', 'Valparaíso'),
  (6101, 'Rancagua', 'Libertador General Bernardo O''Higgins'),
  (6102, 'Codegua', 'Libertador General Bernardo O''Higgins'),
  (6103, 'Coinco', 'Libertador General Bernardo O''Higgins'),
  (6104, 'Coltauco', 'Libertador General Bernardo O''Higgins'),
  (6105, 'Doñihue', 'Libertador General Bernardo O''Higgins'),
  (6106, 'Graneros', 'Libertador General Bernardo O''Higgins'),
  (6107, 'Las Cabras', 'Libertador General Bernardo O''Higgins'),
  (6108, 'Machalí', 'Libertador General Bernardo O''Higgins'),
  (6109, 'Malloa', 'Libertador General Bernardo O''Higgins'),
  (6110, 'Mostazal', 'Libertador General Bernardo O''Higgins'),
  (6111, 'Olivar', 'Libertador General Bernardo O''Higgins'),
  (6112, 'Peumo', 'Libertador General Bernardo O''Higgins'),
  (6113, 'Pichidegua', 'Libertador General Bernardo O''Higgins'),
  (6114, 'Quinta de Tilcoco', 'Libertador General Bernardo O''Higgins'),
  (6115, 'Rengo', 'Libertador General Bernardo O''Higgins'),
  (6116, 'Requínoa', 'Libertador General Bernardo O''Higgins'),
  (6117, 'San Vicente', 'Libertador General Bernardo O''Higgins'),
  (6201, 'Pichilemu', 'Libertador General Bernardo O''Higgins'),
  (6202, 'La Estrella', 'Libertador General Bernardo O''Higgins'),
  (6203, 'Litueche', 'Libertador General Bernardo O''Higgins'),
  (6204, 'Marchigüe', 'Libertador General Bernardo O''Higgins'),
  (6205, 'Navidad', 'Libertador General Bernardo O''Higgins'),
  (6206, 'Paredones', 'Libertador General Bernardo O''Higgins'),
  (6301, 'San Fernando', 'Libertador General Bernardo O''Higgins'),
  (6302, 'Chépica', 'Libertador General Bernardo O''Higgins'),
  (6303, 'Chimbarongo', 'Libertador General Bernardo O''Higgins'),
  (6304, 'Lolol', 'Libertador General Bernardo O''Higgins'),
  (6305, 'Nancagua', 'Libertador General Bernardo O''Higgins'),
  (6306, 'Palmilla', 'Libertador General Bernardo O''Higgins'),
  (6307, 'Peralillo', 'Libertador General Bernardo O''Higgins'),
  (6308, 'Placilla', 'Libertador General Bernardo O''Higgins'),
  (6309, 'Pumanque', 'Libertador General Bernardo O''Higgins'),
  (6310, 'Santa Cruz', 'Libertador General Bernardo O''Higgins'),
  (7101, 'Talca', 'Maule'),
  (7102, 'Constitución', 'Maule'),
  (7103, 'Curepto', 'Maule'),
  (7104, 'Empedrado', 'Maule'),
  (7105, 'Maule', 'Maule'),
  (7106, 'Pelarco', 'Maule'),
  (7107, 'Pencahue', 'Maule'),
  (7108, 'Río Claro', 'Maule'),
  (7109, 'San Clemente', 'Maule'),
  (7110, 'San Rafael', 'Maule'),
  (7201, 'Cauquenes', 'Maule'),
  (7202, 'Chanco', 'Maule'),
  (7203, 'Pelluhue', 'Maule'),
  (7301, 'Curicó', 'Maule'),
  (7302, 'Hualañé', 'Maule'),
  (7303, 'Licantén', 'Maule'),
  (7304, 'Molina', 'Maule'),
  (7305, 'Rauco', 'Maule'),
  (7306, 'Romeral', 'Maule'),
  (7307, 'Sagrada Familia', 'Maule'),
  (7308, 'Teno', 'Maule'),
  (7309, 'Vichuquén', 'Maule'),
  (7401, 'Linares', 'Maule'),
  (7402, 'Colbún', 'Maule'),
  (7403, 'Longaví', 'Maule'),
  (7404, 'Parral', 'Maule'),
  (7405, 'Retiro', 'Maule'),
  (7406, 'San Javier', 'Maule'),
  (7407, 'Villa Alegre', 'Maule'),
  (7408, 'Yerbas Buenas', 'Maule'),
  (8101, 'Concepción', 'Biobío'),
  (8102, 'Coronel', 'Biobío'),
  (8103, 'Chiguayante', 'Biobío'),
  (8104, 'Florida', 'Biobío'),
  (8105, 'Hualqui', 'Biobío'),
  (8106, 'Lota', 'Biobío'),
  (8107, 'Penco', 'Biobío'),
  (8108, 'San Pedro de La Paz', 'Biobío'),
  (8109, 'Santa Juana', 'Biobío'),
  (8110, 'Talcahuano', 'Biobío'),
  (8111, 'Tomé', 'Biobío'),
  (8112, 'Hualpén', 'Biobío'),
  (8201, 'Lebu', 'Biobío'),
  (8202, 'Arauco', 'Biobío'),
  (8203, 'Cañete', 'Biobío'),
  (8204, 'Contulmo', 'Biobío'),
  (8205, 'Curanilahue', 'Biobío'),
  (8206, 'Los Álamos', 'Biobío'),
  (8207, 'Tirúa', 'Biobío'),
  (8301, 'Los Ángeles', 'Biobío'),
  (8302, 'Antuco', 'Biobío'),
  (8303, 'Cabrero', 'Biobío'),
  (8304, 'Laja', 'Biobío'),
  (8305, 'Mulchén', 'Biobío'),
  (8306, 'Nacimiento', 'Biobío'),
  (8307, 'Negrete', 'Biobío'),
  (8308, 'Quilaco', 'Biobío'),
  (8309, 'Quilleco', 'Biobío'),
  (8310, 'San Rosendo', 'Biobío'),
  (8311, 'Santa Bárbara', 'Biobío'),
  (8312, 'Tucapel', 'Biobío'),
  (8313, 'Yumbel', 'Biobío'),
  (8314, 'Alto Biobío', 'Biobío'),
  (9101, 'Temuco', 'La Araucanía'),
  (9102, 'Carahue', 'La Araucanía'),
  (9103, 'Cunco', 'La Araucanía'),
  (9104, 'Curarrehue', 'La Araucanía'),
  (9105, 'Freire', 'La Araucanía'),
  (9106, 'Galvarino', 'La Araucanía'),
  (9107, 'Gorbea', 'La Araucanía'),
  (9108, 'Lautaro', 'La Araucanía'),
  (9109, 'Loncoche', 'La Araucanía'),
  (9110, 'Melipeuco', 'La Araucanía'),
  (9111, 'Nueva Imperial', 'La Araucanía'),
  (9112, 'Padre Las Casas', 'La Araucanía'),
  (9113, 'Perquenco', 'La Araucanía'),
  (9114, 'Pitrufquén', 'La Araucanía'),
  (9115, 'Pucón', 'La Araucanía'),
  (9116, 'Saavedra', 'La Araucanía'),
  (9117, 'Teodoro Schmidt', 'La Araucanía'),
  (9118, 'Toltén', 'La Araucanía'),
  (9119, 'Vilcún', 'La Araucanía'),
  (9120, 'Villarrica', 'La Araucanía'),
  (9121, 'Cholchol', 'La Araucanía'),
  (9201, 'Angol', 'La Araucanía'),
  (9202, 'Collipulli', 'La Araucanía'),
  (9203, 'Curacautín', 'La Araucanía'),
  (9204, 'Ercilla', 'La Araucanía'),
  (9205, 'Lonquimay', 'La Araucanía'),
  (9206, 'Los Sauces', 'La Araucanía'),
  (9207, 'Lumaco', 'La Araucanía'),
  (9208, 'Purén', 'La Araucanía'),
  (9209, 'Renaico', 'La Araucanía'),
  (9210, 'Traiguén', 'La Araucanía'),
  (9211, 'Victoria', 'La Araucanía'),
  (10101, 'Puerto Montt', 'Los Lagos'),
  (10102, 'Calbuco', 'Los Lagos'),
  (10103, 'Cochamó', 'Los Lagos'),
  (10104, 'Fresia', 'Los Lagos'),
  (10105, 'Frutillar', 'Los Lagos'),
  (10106, 'Los Muermos', 'Los Lagos'),
  (10107, 'Llanquihue', 'Los Lagos'),
  (10108, 'Maullín', 'Los Lagos'),
  (10109, 'Puerto Varas', 'Los Lagos'),
  (10201, 'Castro', 'Los Lagos'),
  (10202, 'Ancud', 'Los Lagos'),
  (10203, 'Chonchi', 'Los Lagos'),
  (10204, 'Curaco de Vélez', 'Los Lagos'),
  (10205, 'Dalcahue', 'Los Lagos'),
  (10206, 'Puqueldón', 'Los Lagos'),
  (10207, 'Queilén', 'Los Lagos'),
  (10208, 'Quellón', 'Los Lagos'),
  (10209, 'Quemchi', 'Los Lagos'),
  (10210, 'Quinchao', 'Los Lagos'),
  (10301, 'Osorno', 'Los Lagos'),
  (10302, 'Puerto Octay', 'Los Lagos'),
  (10303, 'Purranque', 'Los Lagos'),
  (10304, 'Puyehue', 'Los Lagos'),
  (10305, 'Río Negro', 'Los Lagos'),
  (10306, 'San Juan de la Costa', 'Los Lagos'),
  (10307, 'San Pablo', 'Los Lagos'),
  (10401, 'Chaitén', 'Los Lagos'),
  (10402, 'Futaleufú', 'Los Lagos'),
  (10403, 'Hualaihué', 'Los Lagos'),
  (10404, 'Palena', 'Los Lagos'),
  (11101, 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo'),
  (11102, 'Lago Verde', 'Aysén del General Carlos Ibáñez del Campo'),
  (11201, 'Aysén', 'Aysén del General Carlos Ibáñez del Campo'),
  (11202, 'Cisnes', 'Aysén del General Carlos Ibáñez del Campo'),
  (11203, 'Guaitecas', 'Aysén del General Carlos Ibáñez del Campo'),
  (11301, 'Cochrane', 'Aysén del General Carlos Ibáñez del Campo'),
  (11302, 'O''Higgins', 'Aysén del General Carlos Ibáñez del Campo'),
  (11303, 'Tortel', 'Aysén del General Carlos Ibáñez del Campo'),
  (11401, 'Chile Chico', 'Aysén del General Carlos Ibáñez del Campo'),
  (11402, 'Río Ibáñez', 'Aysén del General Carlos Ibáñez del Campo'),
  (12101, 'Punta Arenas', 'Magallanes y Antártica Chilena'),
  (12102, 'Laguna Blanca', 'Magallanes y Antártica Chilena'),
  (12103, 'Río Verde', 'Magallanes y Antártica Chilena'),
  (12104, 'San Gregorio', 'Magallanes y Antártica Chilena'),
  (12201, 'Cabo de Hornos', 'Magallanes y Antártica Chilena'),
  (12202, 'Antártica', 'Magallanes y Antártica Chilena'),
  (12301, 'Porvenir', 'Magallanes y Antártica Chilena'),
  (12302, 'Primavera', 'Magallanes y Antártica Chilena'),
  (12303, 'Timaukel', 'Magallanes y Antártica Chilena'),
  (12401, 'Natales', 'Magallanes y Antártica Chilena'),
  (12402, 'Torres del Paine', 'Magallanes y Antártica Chilena'),
  (13101, 'Santiago', 'Metropolitana de Santiago'),
  (13102, 'Cerrillos', 'Metropolitana de Santiago'),
  (13103, 'Cerro Navia', 'Metropolitana de Santiago'),
  (13104, 'Conchalí', 'Metropolitana de Santiago'),
  (13105, 'El Bosque', 'Metropolitana de Santiago'),
  (13106, 'Estación Central', 'Metropolitana de Santiago'),
  (13107, 'Huechuraba', 'Metropolitana de Santiago'),
  (13108, 'Independencia', 'Metropolitana de Santiago'),
  (13109, 'La Cisterna', 'Metropolitana de Santiago'),
  (13110, 'La Florida', 'Metropolitana de Santiago'),
  (13111, 'La Granja', 'Metropolitana de Santiago'),
  (13112, 'La Pintana', 'Metropolitana de Santiago'),
  (13113, 'La Reina', 'Metropolitana de Santiago'),
  (13114, 'Las Condes', 'Metropolitana de Santiago'),
  (13115, 'Lo Barnechea', 'Metropolitana de Santiago'),
  (13116, 'Lo Espejo', 'Metropolitana de Santiago'),
  (13117, 'Lo Prado', 'Metropolitana de Santiago'),
  (13118, 'Macul', 'Metropolitana de Santiago'),
  (13119, 'Maipú', 'Metropolitana de Santiago'),
  (13120, 'Ñuñoa', 'Metropolitana de Santiago'),
  (13121, 'Pedro Aguirre Cerda', 'Metropolitana de Santiago'),
  (13122, 'Peñalolén', 'Metropolitana de Santiago'),
  (13123, 'Providencia', 'Metropolitana de Santiago'),
  (13124, 'Pudahuel', 'Metropolitana de Santiago'),
  (13125, 'Quilicura', 'Metropolitana de Santiago'),
  (13126, 'Quinta Normal', 'Metropolitana de Santiago'),
  (13127, 'Recoleta', 'Metropolitana de Santiago'),
  (13128, 'Renca', 'Metropolitana de Santiago'),
  (13129, 'San Joaquín', 'Metropolitana de Santiago'),
  (13130, 'San Miguel', 'Metropolitana de Santiago'),
  (13131, 'San Ramón', 'Metropolitana de Santiago'),
  (13132, 'Vitacura', 'Metropolitana de Santiago'),
  (13201, 'Puente Alto', 'Metropolitana de Santiago'),
  (13202, 'Pirque', 'Metropolitana de Santiago'),
  (13203, 'San José de Maipo', 'Metropolitana de Santiago'),
  (13301, 'Colina', 'Metropolitana de Santiago'),
  (13302, 'Lampa', 'Metropolitana de Santiago'),
  (13303, 'Til Til', 'Metropolitana de Santiago'),
  (13401, 'San Bernardo', 'Metropolitana de Santiago'),
  (13402, 'Buin', 'Metropolitana de Santiago'),
  (13403, 'Calera de Tango', 'Metropolitana de Santiago'),
  (13404, 'Paine', 'Metropolitana de Santiago'),
  (13501, 'Melipilla', 'Metropolitana de Santiago'),
  (13502, 'Alhué', 'Metropolitana de Santiago'),
  (13503, 'Curacaví', 'Metropolitana de Santiago'),
  (13504, 'María Pinto', 'Metropolitana de Santiago'),
  (13505, 'San Pedro', 'Metropolitana de Santiago'),
  (13601, 'Talagante', 'Metropolitana de Santiago'),
  (13602, 'El Monte', 'Metropolitana de Santiago'),
  (13603, 'Isla de Maipo', 'Metropolitana de Santiago'),
  (13604, 'Padre Hurtado', 'Metropolitana de Santiago'),
  (13605, 'Peñaflor', 'Metropolitana de Santiago'),
  (14101, 'Valdivia', 'Los Ríos'),
  (14102, 'Corral', 'Los Ríos'),
  (14103, 'Lanco', 'Los Ríos'),
  (14104, 'Los Lagos', 'Los Ríos'),
  (14105, 'Máfil', 'Los Ríos'),
  (14106, 'Mariquina', 'Los Ríos'),
  (14107, 'Paillaco', 'Los Ríos'),
  (14108, 'Panguipulli', 'Los Ríos'),
  (14201, 'La Unión', 'Los Ríos'),
  (14202, 'Futrono', 'Los Ríos'),
  (14203, 'Lago Ranco', 'Los Ríos'),
  (14204, 'Río Bueno', 'Los Ríos'),
  (15101, 'Arica', 'Arica y Parinacota'),
  (15102, 'Camarones', 'Arica y Parinacota'),
  (15201, 'Putre', 'Arica y Parinacota'),
  (15202, 'General Lagos', 'Arica y Parinacota'),
  (16101, 'Chillán', 'Ñuble'),
  (16102, 'Bulnes', 'Ñuble'),
  (16103, 'Chillán Viejo', 'Ñuble'),
  (16104, 'El Carmen', 'Ñuble'),
  (16105, 'Pemuco', 'Ñuble'),
  (16106, 'Pinto', 'Ñuble'),
  (16107, 'Quillón', 'Ñuble'),
  (16108, 'San Ignacio', 'Ñuble'),
  (16109, 'Yungay', 'Ñuble'),
  (16201, 'Quirihue', 'Ñuble'),
  (16202, 'Cobquecura', 'Ñuble'),
  (16203, 'Coelemu', 'Ñuble'),
  (16204, 'Ninhue', 'Ñuble'),
  (16205, 'Portezuelo', 'Ñuble'),
  (16206, 'Ránquil', 'Ñuble'),
  (16207, 'Treguaco', 'Ñuble'),
  (16301, 'San Carlos', 'Ñuble'),
  (16302, 'Coihueco', 'Ñuble'),
  (16303, 'Ñiquén', 'Ñuble'),
  (16304, 'San Fabián', 'Ñuble'),
  (16305, 'San Nicolás', 'Ñuble');

-- 1. Nueva columna, todavía nullable para poder poblarla.
ALTER TABLE "universidad" ADD COLUMN "codigo_comuna" INTEGER;

-- 2. Enlace por texto normalizado. Postgres no trae `unaccent` por defecto, así
--    que las tildes se quitan con translate().
UPDATE "universidad" u
SET "codigo_comuna" = c."codigo_comuna"
FROM "comuna" c
WHERE regexp_replace(translate(lower(u."comuna"), 'áéíóúüñ', 'aeiouun'), '[^a-z0-9]', '', 'g')
    = regexp_replace(translate(lower(c."nombre"), 'áéíóúüñ', 'aeiouun'), '[^a-z0-9]', '', 'g');

-- 3. Alias conocidos: nombres de ciudad que no son el nombre de la comuna.
UPDATE "universidad" SET "codigo_comuna" = 12401  -- Natales
WHERE "codigo_comuna" IS NULL AND lower(trim("comuna")) = 'puerto natales';

-- 4. Si queda alguna sin enlazar, se aborta todo (ROLLBACK implícito) y el
--    error lista las filas para corregirlas a mano antes de reintentar.
DO $$
DECLARE
  sin_comuna TEXT;
BEGIN
  SELECT string_agg(format('#%s %s (%s)', "codigo_universidad", "nombre", "comuna"), '; ')
    INTO sin_comuna
    FROM "universidad"
   WHERE "codigo_comuna" IS NULL;
  IF sin_comuna IS NOT NULL THEN
    RAISE EXCEPTION 'Universidades cuya comuna no se encontró en el catálogo: %', sin_comuna;
  END IF;
END $$;

-- 5. Recién ahora, con todo enlazado, se reemplaza la columna de texto.
ALTER TABLE "universidad" ALTER COLUMN "codigo_comuna" SET NOT NULL;
ALTER TABLE "universidad" ADD CONSTRAINT "universidad_codigo_comuna_fkey"
  FOREIGN KEY ("codigo_comuna") REFERENCES "comuna"("codigo_comuna") ON DELETE RESTRICT ON UPDATE CASCADE;

DROP INDEX "universidad_nombre_comuna_key";
CREATE UNIQUE INDEX "universidad_nombre_codigo_comuna_key" ON "universidad"("nombre", "codigo_comuna");
ALTER TABLE "universidad" DROP COLUMN "comuna";

COMMIT;
